// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file lain.proto (package lain.viz, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Only id and value; kind deferred to later iteration.
 *
 * @generated from message lain.viz.CardRef
 */
export class CardRef extends Message<CardRef> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * JSON-serialized
   *
   * @generated from field: bytes value = 2;
   */
  value = new Uint8Array(0);

  constructor(data?: PartialMessage<CardRef>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardRef";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardRef {
    return new CardRef().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardRef {
    return new CardRef().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardRef {
    return new CardRef().fromJsonString(jsonString, options);
  }

  static equals(a: CardRef | PlainMessage<CardRef> | undefined, b: CardRef | PlainMessage<CardRef> | undefined): boolean {
    return proto3.util.equals(CardRef, a, b);
  }
}

/**
 * Code is data: unified map of slot -> value. Slots: "code", "::above", "::below", "::this"
 *
 * @generated from message lain.viz.CompileRequest
 */
export class CompileRequest extends Message<CompileRequest> {
  /**
   * @generated from field: map<string, lain.viz.CardRef> data = 1;
   */
  data: { [key: string]: CardRef } = {};

  constructor(data?: PartialMessage<CompileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CompileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: CardRef} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompileRequest {
    return new CompileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompileRequest {
    return new CompileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompileRequest {
    return new CompileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CompileRequest | PlainMessage<CompileRequest> | undefined, b: CompileRequest | PlainMessage<CompileRequest> | undefined): boolean {
    return proto3.util.equals(CompileRequest, a, b);
  }
}

/**
 * Strongest value decomposed per Propogator traced-timestamp system.
 * Interface: source_id = cell name. Dataflow: source_id = cell_id.
 *
 * @generated from message lain.viz.StrongestValueLayer
 */
export class StrongestValueLayer extends Message<StrongestValueLayer> {
  /**
   * JSON-serialized base value
   *
   * @generated from field: bytes value = 1;
   */
  value = new Uint8Array(0);

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * cell_id in dataflow; cell name at interface
   *
   * @generated from field: string source_id = 3;
   */
  sourceId = "";

  constructor(data?: PartialMessage<StrongestValueLayer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.StrongestValueLayer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "source_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromJsonString(jsonString, options);
  }

  static equals(a: StrongestValueLayer | PlainMessage<StrongestValueLayer> | undefined, b: StrongestValueLayer | PlainMessage<StrongestValueLayer> | undefined): boolean {
    return proto3.util.equals(StrongestValueLayer, a, b);
  }
}

/**
 * Network update: real-time I/O with flexible visualization (more than visualization).
 *
 * @generated from message lain.viz.NetworkUpdate
 */
export class NetworkUpdate extends Message<NetworkUpdate> {
  /**
   * @generated from field: string cell_id = 1;
   */
  cellId = "";

  /**
   * cell name for interface display
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: lain.viz.StrongestValueLayer strongest_value = 3;
   */
  strongestValue?: StrongestValueLayer;

  constructor(data?: PartialMessage<NetworkUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.NetworkUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cell_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "strongest_value", kind: "message", T: StrongestValueLayer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: NetworkUpdate | PlainMessage<NetworkUpdate> | undefined, b: NetworkUpdate | PlainMessage<NetworkUpdate> | undefined): boolean {
    return proto3.util.equals(NetworkUpdate, a, b);
  }
}

/**
 * Only success or error_message; NetworkStream provides all network updates.
 *
 * @generated from message lain.viz.CompileResponse
 */
export class CompileResponse extends Message<CompileResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * empty when success
   *
   * @generated from field: string error_message = 2;
   */
  errorMessage = "";

  constructor(data?: PartialMessage<CompileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CompileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompileResponse {
    return new CompileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompileResponse {
    return new CompileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompileResponse {
    return new CompileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CompileResponse | PlainMessage<CompileResponse> | undefined, b: CompileResponse | PlainMessage<CompileResponse> | undefined): boolean {
    return proto3.util.equals(CompileResponse, a, b);
  }
}

