// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file lain.proto (package lain.viz, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CardBuildRequest, CardBuildResponse, CardsDelta, CompileRequest, CompileResponse, Empty, NetworkUpdate, OpenSessionRequest, PushDeltasRequest, ServerMessage } from "./lain_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Browser client (lain-viz): use OpenSession + PushDeltas + CardBuild only.
 *
 * @generated from service lain.viz.LainViz
 */
export const LainViz = {
  typeName: "lain.viz.LainViz",
  methods: {
    /**
     * Deprecated: not used by lain-viz; server handler was a stub (`compile_for_viz` / no-op bind). Prefer PushDeltas + CardBuild.
     *
     * @generated from rpc lain.viz.LainViz.Compile
     * @deprecated
     */
    compile: {
      name: "Compile",
      I: CompileRequest,
      O: CompileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deprecated: not used by lain-viz; legacy server stream (heartbeats stub). Prefer OpenSession for outbound updates.
     *
     * @generated from rpc lain.viz.LainViz.NetworkStream
     * @deprecated
     */
    networkStream: {
      name: "NetworkStream",
      I: CompileRequest,
      O: NetworkUpdate,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Deprecated: not used by lain-viz; non-browser bidi path. Prefer OpenSession + PushDeltas.
     *
     * @generated from rpc lain.viz.LainViz.Session
     * @deprecated
     */
    session: {
      name: "Session",
      I: CardsDelta,
      O: ServerMessage,
      kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc lain.viz.LainViz.OpenSession
     */
    openSession: {
      name: "OpenSession",
      I: OpenSessionRequest,
      O: ServerMessage,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc lain.viz.LainViz.PushDeltas
     */
    pushDeltas: {
      name: "PushDeltas",
      I: PushDeltasRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc lain.viz.LainViz.CardBuild
     */
    cardBuild: {
      name: "CardBuild",
      I: CardBuildRequest,
      O: CardBuildResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

