// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file lain.proto (package lain.viz, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Only id and value; kind deferred to later iteration.
 *
 * @generated from message lain.viz.CardRef
 */
export class CardRef extends Message<CardRef> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * JSON-serialized
   *
   * @generated from field: bytes value = 2;
   */
  value = new Uint8Array(0);

  constructor(data?: PartialMessage<CardRef>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardRef";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardRef {
    return new CardRef().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardRef {
    return new CardRef().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardRef {
    return new CardRef().fromJsonString(jsonString, options);
  }

  static equals(a: CardRef | PlainMessage<CardRef> | undefined, b: CardRef | PlainMessage<CardRef> | undefined): boolean {
    return proto3.util.equals(CardRef, a, b);
  }
}

/**
 * Code is data: unified map of slot -> value. Slots: "code", "::above", "::below", "::this"
 *
 * @generated from message lain.viz.CompileRequest
 */
export class CompileRequest extends Message<CompileRequest> {
  /**
   * @generated from field: map<string, lain.viz.CardRef> data = 1;
   */
  data: { [key: string]: CardRef } = {};

  constructor(data?: PartialMessage<CompileRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CompileRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: CardRef} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompileRequest {
    return new CompileRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompileRequest {
    return new CompileRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompileRequest {
    return new CompileRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CompileRequest | PlainMessage<CompileRequest> | undefined, b: CompileRequest | PlainMessage<CompileRequest> | undefined): boolean {
    return proto3.util.equals(CompileRequest, a, b);
  }
}

/**
 * Strongest value decomposed per Propogator traced-timestamp system.
 * Interface: source_id = cell name. Dataflow: source_id = cell_id.
 *
 * @generated from message lain.viz.StrongestValueLayer
 */
export class StrongestValueLayer extends Message<StrongestValueLayer> {
  /**
   * JSON-serialized base value
   *
   * @generated from field: bytes value = 1;
   */
  value = new Uint8Array(0);

  /**
   * @generated from field: int64 timestamp = 2;
   */
  timestamp = protoInt64.zero;

  /**
   * cell_id in dataflow; cell name at interface
   *
   * @generated from field: string source_id = 3;
   */
  sourceId = "";

  constructor(data?: PartialMessage<StrongestValueLayer>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.StrongestValueLayer";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "source_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StrongestValueLayer {
    return new StrongestValueLayer().fromJsonString(jsonString, options);
  }

  static equals(a: StrongestValueLayer | PlainMessage<StrongestValueLayer> | undefined, b: StrongestValueLayer | PlainMessage<StrongestValueLayer> | undefined): boolean {
    return proto3.util.equals(StrongestValueLayer, a, b);
  }
}

/**
 * Network update: real-time I/O with flexible visualization (more than visualization).
 *
 * @generated from message lain.viz.NetworkUpdate
 */
export class NetworkUpdate extends Message<NetworkUpdate> {
  /**
   * @generated from field: string cell_id = 1;
   */
  cellId = "";

  /**
   * cell name for interface display
   *
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: lain.viz.StrongestValueLayer strongest_value = 3;
   */
  strongestValue?: StrongestValueLayer;

  constructor(data?: PartialMessage<NetworkUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.NetworkUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "cell_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "strongest_value", kind: "message", T: StrongestValueLayer },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NetworkUpdate {
    return new NetworkUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: NetworkUpdate | PlainMessage<NetworkUpdate> | undefined, b: NetworkUpdate | PlainMessage<NetworkUpdate> | undefined): boolean {
    return proto3.util.equals(NetworkUpdate, a, b);
  }
}

/**
 * Only success or error_message; NetworkStream provides all network updates.
 *
 * @generated from message lain.viz.CompileResponse
 */
export class CompileResponse extends Message<CompileResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * empty when success
   *
   * @generated from field: string error_message = 2;
   */
  errorMessage = "";

  constructor(data?: PartialMessage<CompileResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CompileResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompileResponse {
    return new CompileResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompileResponse {
    return new CompileResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompileResponse {
    return new CompileResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CompileResponse | PlainMessage<CompileResponse> | undefined, b: CompileResponse | PlainMessage<CompileResponse> | undefined): boolean {
    return proto3.util.equals(CompileResponse, a, b);
  }
}

/**
 * Delta from frontend: slots to set (key -> CardRef) and keys to remove.
 *
 * @generated from message lain.viz.CardsDelta
 */
export class CardsDelta extends Message<CardsDelta> {
  /**
   * set/update; key present = set
   *
   * @generated from field: map<string, lain.viz.CardRef> slots = 1;
   */
  slots: { [key: string]: CardRef } = {};

  /**
   * keys to remove (e.g. neighbor detached)
   *
   * @generated from field: repeated string remove = 2;
   */
  remove: string[] = [];

  constructor(data?: PartialMessage<CardsDelta>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardsDelta";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slots", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: CardRef} },
    { no: 2, name: "remove", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardsDelta {
    return new CardsDelta().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardsDelta {
    return new CardsDelta().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardsDelta {
    return new CardsDelta().fromJsonString(jsonString, options);
  }

  static equals(a: CardsDelta | PlainMessage<CardsDelta> | undefined, b: CardsDelta | PlainMessage<CardsDelta> | undefined): boolean {
    return proto3.util.equals(CardsDelta, a, b);
  }
}

/**
 * Backend -> frontend: heartbeat (connection) or card update (id, slot, value).
 *
 * @generated from message lain.viz.Heartbeat
 */
export class Heartbeat extends Message<Heartbeat> {
  constructor(data?: PartialMessage<Heartbeat>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.Heartbeat";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Heartbeat {
    return new Heartbeat().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Heartbeat {
    return new Heartbeat().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Heartbeat {
    return new Heartbeat().fromJsonString(jsonString, options);
  }

  static equals(a: Heartbeat | PlainMessage<Heartbeat> | undefined, b: Heartbeat | PlainMessage<Heartbeat> | undefined): boolean {
    return proto3.util.equals(Heartbeat, a, b);
  }
}

/**
 * @generated from message lain.viz.CardUpdate
 */
export class CardUpdate extends Message<CardUpdate> {
  /**
   * @generated from field: string card_id = 1;
   */
  cardId = "";

  /**
   * e.g. "::above", "code", "::this"
   *
   * @generated from field: string slot = 2;
   */
  slot = "";

  /**
   * empty/missing = remove card for this slot
   *
   * @generated from field: lain.viz.CardRef ref = 3;
   */
  ref?: CardRef;

  constructor(data?: PartialMessage<CardUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "card_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slot", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "ref", kind: "message", T: CardRef },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardUpdate {
    return new CardUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardUpdate {
    return new CardUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardUpdate {
    return new CardUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: CardUpdate | PlainMessage<CardUpdate> | undefined, b: CardUpdate | PlainMessage<CardUpdate> | undefined): boolean {
    return proto3.util.equals(CardUpdate, a, b);
  }
}

/**
 * @generated from message lain.viz.ServerMessage
 */
export class ServerMessage extends Message<ServerMessage> {
  /**
   * @generated from oneof lain.viz.ServerMessage.kind
   */
  kind: {
    /**
     * @generated from field: lain.viz.Heartbeat heartbeat = 1;
     */
    value: Heartbeat;
    case: "heartbeat";
  } | {
    /**
     * @generated from field: lain.viz.CardUpdate card_update = 2;
     */
    value: CardUpdate;
    case: "cardUpdate";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<ServerMessage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.ServerMessage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "heartbeat", kind: "message", T: Heartbeat, oneof: "kind" },
    { no: 2, name: "card_update", kind: "message", T: CardUpdate, oneof: "kind" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerMessage {
    return new ServerMessage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerMessage {
    return new ServerMessage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerMessage {
    return new ServerMessage().fromJsonString(jsonString, options);
  }

  static equals(a: ServerMessage | PlainMessage<ServerMessage> | undefined, b: ServerMessage | PlainMessage<ServerMessage> | undefined): boolean {
    return proto3.util.equals(ServerMessage, a, b);
  }
}

/**
 * Browser-compatible: one request (no client streaming). Client sends session_id + initial state.
 *
 * @generated from message lain.viz.OpenSessionRequest
 */
export class OpenSessionRequest extends Message<OpenSessionRequest> {
  /**
   * client-generated; used for PushDeltas/CardBuild
   *
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * optional initial slot map
   *
   * @generated from field: lain.viz.CompileRequest initial_data = 2;
   */
  initialData?: CompileRequest;

  constructor(data?: PartialMessage<OpenSessionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.OpenSessionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "initial_data", kind: "message", T: CompileRequest },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OpenSessionRequest {
    return new OpenSessionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OpenSessionRequest {
    return new OpenSessionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OpenSessionRequest {
    return new OpenSessionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: OpenSessionRequest | PlainMessage<OpenSessionRequest> | undefined, b: OpenSessionRequest | PlainMessage<OpenSessionRequest> | undefined): boolean {
    return proto3.util.equals(OpenSessionRequest, a, b);
  }
}

/**
 * Unary: apply delta to session. Browser can call this; no client stream needed.
 *
 * @generated from message lain.viz.PushDeltasRequest
 */
export class PushDeltasRequest extends Message<PushDeltasRequest> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: lain.viz.CardsDelta delta = 2;
   */
  delta?: CardsDelta;

  constructor(data?: PartialMessage<PushDeltasRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.PushDeltasRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "delta", kind: "message", T: CardsDelta },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushDeltasRequest {
    return new PushDeltasRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushDeltasRequest {
    return new PushDeltasRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushDeltasRequest {
    return new PushDeltasRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PushDeltasRequest | PlainMessage<PushDeltasRequest> | undefined, b: PushDeltasRequest | PlainMessage<PushDeltasRequest> | undefined): boolean {
    return proto3.util.equals(PushDeltasRequest, a, b);
  }
}

/**
 * Manual build trigger for one card in a session.
 *
 * @generated from message lain.viz.CardBuildRequest
 */
export class CardBuildRequest extends Message<CardBuildRequest> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId = "";

  /**
   * @generated from field: string card_id = 2;
   */
  cardId = "";

  constructor(data?: PartialMessage<CardBuildRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardBuildRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "card_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardBuildRequest {
    return new CardBuildRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardBuildRequest {
    return new CardBuildRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardBuildRequest {
    return new CardBuildRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CardBuildRequest | PlainMessage<CardBuildRequest> | undefined, b: CardBuildRequest | PlainMessage<CardBuildRequest> | undefined): boolean {
    return proto3.util.equals(CardBuildRequest, a, b);
  }
}

/**
 * @generated from message lain.viz.CardBuildResponse
 */
export class CardBuildResponse extends Message<CardBuildResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string error_message = 2;
   */
  errorMessage = "";

  constructor(data?: PartialMessage<CardBuildResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.CardBuildResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CardBuildResponse {
    return new CardBuildResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CardBuildResponse {
    return new CardBuildResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CardBuildResponse {
    return new CardBuildResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CardBuildResponse | PlainMessage<CardBuildResponse> | undefined, b: CardBuildResponse | PlainMessage<CardBuildResponse> | undefined): boolean {
    return proto3.util.equals(CardBuildResponse, a, b);
  }
}

/**
 * @generated from message lain.viz.Empty
 */
export class Empty extends Message<Empty> {
  constructor(data?: PartialMessage<Empty>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "lain.viz.Empty";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Empty {
    return new Empty().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Empty {
    return new Empty().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Empty {
    return new Empty().fromJsonString(jsonString, options);
  }

  static equals(a: Empty | PlainMessage<Empty> | undefined, b: Empty | PlainMessage<Empty> | undefined): boolean {
    return proto3.util.equals(Empty, a, b);
  }
}

